services:
  app:
    build: .
    container_name: simple-python-server
    command: ./setup.sh #uvicorn app:app --host 0.0.0.0 --port 9000 --reload
    ports:
      - 9000:8000
    volumes:
      - .:/app